/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Fit.ai API
 * API documentation for Fit.ai
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../axios-instance";
export type ListWorkoutPlansParams = {
  active?: string;
};

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans400 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan400 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay400 = {
  error: string;
  code: string;
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type UpdateWorkoutSession400 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activeWorkoutPlanId: string | null;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData400 = {
  error: string;
  code: string;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats400 = {
  error: string;
  code: string;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type ChatWithAiBodyMessagesItemRole =
  (typeof ChatWithAiBodyMessagesItemRole)[keyof typeof ChatWithAiBodyMessagesItemRole];

export const ChatWithAiBodyMessagesItemRole = {
  system: "system",
  user: "user",
  assistant: "assistant",
} as const;

export type ChatWithAiBodyMessagesItem = {
  role: ChatWithAiBodyMessagesItemRole;
  [key: string]: unknown;
};

export type ChatWithAiBody = {
  messages: ChatWithAiBodyMessagesItem[];
};

export type ChatWithAi401 = {
  error: string;
  code: string;
};

export type ChatWithAi500 = {
  error: string;
  code: string;
};

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List workout plans, optionally filtered by active status
 */
export const listWorkoutPlans = (
  params?: ListWorkoutPlansParams,
  signal?: AbortSignal,
) => {
  return customInstance<ListWorkoutPlans200Item[]>({
    url: `/workout-plans/`,
    method: "GET",
    params,
    signal,
  });
};

export const getListWorkoutPlansQueryKey = (
  params?: ListWorkoutPlansParams,
) => {
  return [`/workout-plans/`, ...(params ? [params] : [])] as const;
};

export const getListWorkoutPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof listWorkoutPlans>>,
  TError = ListWorkoutPlans400 | ListWorkoutPlans401 | ListWorkoutPlans500,
>(
  params?: ListWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listWorkoutPlans>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListWorkoutPlansQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listWorkoutPlans>>
  > = ({ signal }) => listWorkoutPlans(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listWorkoutPlans>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListWorkoutPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof listWorkoutPlans>>
>;
export type ListWorkoutPlansQueryError =
  | ListWorkoutPlans400
  | ListWorkoutPlans401
  | ListWorkoutPlans500;

export function useListWorkoutPlans<
  TData = Awaited<ReturnType<typeof listWorkoutPlans>>,
  TError = ListWorkoutPlans400 | ListWorkoutPlans401 | ListWorkoutPlans500,
>(
  params: undefined | ListWorkoutPlansParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listWorkoutPlans>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutPlans>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListWorkoutPlans<
  TData = Awaited<ReturnType<typeof listWorkoutPlans>>,
  TError = ListWorkoutPlans400 | ListWorkoutPlans401 | ListWorkoutPlans500,
>(
  params?: ListWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listWorkoutPlans>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutPlans>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListWorkoutPlans<
  TData = Awaited<ReturnType<typeof listWorkoutPlans>>,
  TError = ListWorkoutPlans400 | ListWorkoutPlans401 | ListWorkoutPlans500,
>(
  params?: ListWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listWorkoutPlans>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List workout plans, optionally filtered by active status
 */

export function useListWorkoutPlans<
  TData = Awaited<ReturnType<typeof listWorkoutPlans>>,
  TError = ListWorkoutPlans400 | ListWorkoutPlans401 | ListWorkoutPlans500,
>(
  params?: ListWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listWorkoutPlans>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListWorkoutPlansQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Create a new workout plan
 */
export const createWorkoutPlan = (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  signal?: AbortSignal,
) => {
  return customInstance<CreateWorkoutPlan201>({
    url: `/workout-plans/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createWorkoutPlanBody,
    signal,
  });
};

export const getCreateWorkoutPlanMutationOptions = <
  TError =
    | CreateWorkoutPlan400
    | CreateWorkoutPlan401
    | CreateWorkoutPlan404
    | CreateWorkoutPlan500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWorkoutPlan>>,
    TError,
    { data: CreateWorkoutPlanBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWorkoutPlan>>,
  TError,
  { data: CreateWorkoutPlanBody },
  TContext
> => {
  const mutationKey = ["createWorkoutPlan"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWorkoutPlan>>,
    { data: CreateWorkoutPlanBody }
  > = (props) => {
    const { data } = props ?? {};

    return createWorkoutPlan(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWorkoutPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWorkoutPlan>>
>;
export type CreateWorkoutPlanMutationBody = CreateWorkoutPlanBody;
export type CreateWorkoutPlanMutationError =
  | CreateWorkoutPlan400
  | CreateWorkoutPlan401
  | CreateWorkoutPlan404
  | CreateWorkoutPlan500;

/**
 * @summary Create a new workout plan
 */
export const useCreateWorkoutPlan = <
  TError =
    | CreateWorkoutPlan400
    | CreateWorkoutPlan401
    | CreateWorkoutPlan404
    | CreateWorkoutPlan500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWorkoutPlan>>,
      TError,
      { data: CreateWorkoutPlanBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWorkoutPlan>>,
  TError,
  { data: CreateWorkoutPlanBody },
  TContext
> => {
  return useMutation(getCreateWorkoutPlanMutationOptions(options), queryClient);
};

/**
 * @summary Get a workout plan by id
 */
export const getWorkoutPlan = (id: string, signal?: AbortSignal) => {
  return customInstance<GetWorkoutPlan200>({
    url: `/workout-plans/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetWorkoutPlanQueryKey = (id: string) => {
  return [`/workout-plans/${id}`] as const;
};

export const getGetWorkoutPlanQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError =
    | GetWorkoutPlan400
    | GetWorkoutPlan401
    | GetWorkoutPlan404
    | GetWorkoutPlan500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWorkoutPlanQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutPlan>>> = ({
    signal,
  }) => getWorkoutPlan(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkoutPlan>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkoutPlanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutPlan>>
>;
export type GetWorkoutPlanQueryError =
  | GetWorkoutPlan400
  | GetWorkoutPlan401
  | GetWorkoutPlan404
  | GetWorkoutPlan500;

export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError =
    | GetWorkoutPlan400
    | GetWorkoutPlan401
    | GetWorkoutPlan404
    | GetWorkoutPlan500,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError =
    | GetWorkoutPlan400
    | GetWorkoutPlan401
    | GetWorkoutPlan404
    | GetWorkoutPlan500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError =
    | GetWorkoutPlan400
    | GetWorkoutPlan401
    | GetWorkoutPlan404
    | GetWorkoutPlan500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a workout plan by id
 */

export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError =
    | GetWorkoutPlan400
    | GetWorkoutPlan401
    | GetWorkoutPlan404
    | GetWorkoutPlan500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkoutPlanQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get a workout day with its exercises and sessions
 */
export const getWorkoutDay = (
  workoutPlanId: string,
  workoutDayId: string,
  signal?: AbortSignal,
) => {
  return customInstance<GetWorkoutDay200>({
    url: `/workout-plans/${workoutPlanId}/days/${workoutDayId}`,
    method: "GET",
    signal,
  });
};

export const getGetWorkoutDayQueryKey = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return [`/workout-plans/${workoutPlanId}/days/${workoutDayId}`] as const;
};

export const getGetWorkoutDayQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError =
    | GetWorkoutDay400
    | GetWorkoutDay401
    | GetWorkoutDay404
    | GetWorkoutDay500,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetWorkoutDayQueryKey(workoutPlanId, workoutDayId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutDay>>> = ({
    signal,
  }) => getWorkoutDay(workoutPlanId, workoutDayId, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      workoutPlanId !== null &&
      workoutPlanId !== undefined &&
      workoutDayId !== null &&
      workoutDayId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkoutDay>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkoutDayQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutDay>>
>;
export type GetWorkoutDayQueryError =
  | GetWorkoutDay400
  | GetWorkoutDay401
  | GetWorkoutDay404
  | GetWorkoutDay500;

export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError =
    | GetWorkoutDay400
    | GetWorkoutDay401
    | GetWorkoutDay404
    | GetWorkoutDay500,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDay>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDay>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError =
    | GetWorkoutDay400
    | GetWorkoutDay401
    | GetWorkoutDay404
    | GetWorkoutDay500,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDay>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDay>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError =
    | GetWorkoutDay400
    | GetWorkoutDay401
    | GetWorkoutDay404
    | GetWorkoutDay500,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a workout day with its exercises and sessions
 */

export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError =
    | GetWorkoutDay400
    | GetWorkoutDay401
    | GetWorkoutDay404
    | GetWorkoutDay500,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkoutDayQueryOptions(
    workoutPlanId,
    workoutDayId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Start a workout session for a workout day
 */
export const startWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string,
  signal?: AbortSignal,
) => {
  return customInstance<StartWorkoutSession201>({
    url: `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`,
    method: "POST",
    signal,
  });
};

export const getStartWorkoutSessionMutationOptions = <
  TError =
    | StartWorkoutSession400
    | StartWorkoutSession401
    | StartWorkoutSession404
    | StartWorkoutSession409
    | StartWorkoutSession500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startWorkoutSession>>,
    TError,
    { workoutPlanId: string; workoutDayId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof startWorkoutSession>>,
  TError,
  { workoutPlanId: string; workoutDayId: string },
  TContext
> => {
  const mutationKey = ["startWorkoutSession"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startWorkoutSession>>,
    { workoutPlanId: string; workoutDayId: string }
  > = (props) => {
    const { workoutPlanId, workoutDayId } = props ?? {};

    return startWorkoutSession(workoutPlanId, workoutDayId);
  };

  return { mutationFn, ...mutationOptions };
};

export type StartWorkoutSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof startWorkoutSession>>
>;

export type StartWorkoutSessionMutationError =
  | StartWorkoutSession400
  | StartWorkoutSession401
  | StartWorkoutSession404
  | StartWorkoutSession409
  | StartWorkoutSession500;

/**
 * @summary Start a workout session for a workout day
 */
export const useStartWorkoutSession = <
  TError =
    | StartWorkoutSession400
    | StartWorkoutSession401
    | StartWorkoutSession404
    | StartWorkoutSession409
    | StartWorkoutSession500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startWorkoutSession>>,
      TError,
      { workoutPlanId: string; workoutDayId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startWorkoutSession>>,
  TError,
  { workoutPlanId: string; workoutDayId: string },
  TContext
> => {
  return useMutation(
    getStartWorkoutSessionMutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Update a workout session
 */
export const updateWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string,
  workoutSessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  signal?: AbortSignal,
) => {
  return customInstance<UpdateWorkoutSession200>({
    url: `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${workoutSessionId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateWorkoutSessionBody,
    signal,
  });
};

export const getUpdateWorkoutSessionMutationOptions = <
  TError =
    | UpdateWorkoutSession400
    | UpdateWorkoutSession401
    | UpdateWorkoutSession404
    | UpdateWorkoutSession500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWorkoutSession>>,
    TError,
    {
      workoutPlanId: string;
      workoutDayId: string;
      workoutSessionId: string;
      data: UpdateWorkoutSessionBody;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateWorkoutSession>>,
  TError,
  {
    workoutPlanId: string;
    workoutDayId: string;
    workoutSessionId: string;
    data: UpdateWorkoutSessionBody;
  },
  TContext
> => {
  const mutationKey = ["updateWorkoutSession"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateWorkoutSession>>,
    {
      workoutPlanId: string;
      workoutDayId: string;
      workoutSessionId: string;
      data: UpdateWorkoutSessionBody;
    }
  > = (props) => {
    const { workoutPlanId, workoutDayId, workoutSessionId, data } = props ?? {};

    return updateWorkoutSession(
      workoutPlanId,
      workoutDayId,
      workoutSessionId,
      data,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateWorkoutSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateWorkoutSession>>
>;
export type UpdateWorkoutSessionMutationBody = UpdateWorkoutSessionBody;
export type UpdateWorkoutSessionMutationError =
  | UpdateWorkoutSession400
  | UpdateWorkoutSession401
  | UpdateWorkoutSession404
  | UpdateWorkoutSession500;

/**
 * @summary Update a workout session
 */
export const useUpdateWorkoutSession = <
  TError =
    | UpdateWorkoutSession400
    | UpdateWorkoutSession401
    | UpdateWorkoutSession404
    | UpdateWorkoutSession500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateWorkoutSession>>,
      TError,
      {
        workoutPlanId: string;
        workoutDayId: string;
        workoutSessionId: string;
        data: UpdateWorkoutSessionBody;
      },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateWorkoutSession>>,
  TError,
  {
    workoutPlanId: string;
    workoutDayId: string;
    workoutSessionId: string;
    data: UpdateWorkoutSessionBody;
  },
  TContext
> => {
  return useMutation(
    getUpdateWorkoutSessionMutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Get home data for the authenticated user
 */
export const getHomeData = (date: string, signal?: AbortSignal) => {
  return customInstance<GetHomeData200>({
    url: `/home/${date}`,
    method: "GET",
    signal,
  });
};

export const getGetHomeDataQueryKey = (date: string) => {
  return [`/home/${date}`] as const;
};

export const getGetHomeDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = GetHomeData400 | GetHomeData401 | GetHomeData500,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHomeDataQueryKey(date);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHomeData>>> = ({
    signal,
  }) => getHomeData(date, signal);

  return {
    queryKey,
    queryFn,
    enabled: date !== null && date !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHomeData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHomeDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHomeData>>
>;
export type GetHomeDataQueryError =
  | GetHomeData400
  | GetHomeData401
  | GetHomeData500;

export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = GetHomeData400 | GetHomeData401 | GetHomeData500,
>(
  date: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHomeData>>,
          TError,
          Awaited<ReturnType<typeof getHomeData>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = GetHomeData400 | GetHomeData401 | GetHomeData500,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHomeData>>,
          TError,
          Awaited<ReturnType<typeof getHomeData>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = GetHomeData400 | GetHomeData401 | GetHomeData500,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get home data for the authenticated user
 */

export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = GetHomeData400 | GetHomeData401 | GetHomeData500,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHomeDataQueryOptions(date, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get workout stats for the authenticated user within a period
 */
export const getStats = (params: GetStatsParams, signal?: AbortSignal) => {
  return customInstance<GetStats200>({
    url: `/stats/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetStatsQueryKey = (params?: GetStatsParams) => {
  return [`/stats/`, ...(params ? [params] : [])] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = GetStats400 | GetStats401 | GetStats500,
>(
  params: GetStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = GetStats400 | GetStats401 | GetStats500;

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = GetStats400 | GetStats401 | GetStats500,
>(
  params: GetStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = GetStats400 | GetStats401 | GetStats500,
>(
  params: GetStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = GetStats400 | GetStats401 | GetStats500,
>(
  params: GetStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get workout stats for the authenticated user within a period
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = GetStats400 | GetStats401 | GetStats500,
>(
  params: GetStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStatsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get train data for the authenticated user
 */
export const getUserTrainData = (signal?: AbortSignal) => {
  return customInstance<GetUserTrainData200>({
    url: `/me/`,
    method: "GET",
    signal,
  });
};

export const getGetUserTrainDataQueryKey = () => {
  return [`/me/`] as const;
};

export const getGetUserTrainDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserTrainData>>,
  TError = GetUserTrainData401 | GetUserTrainData500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserTrainData>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserTrainDataQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserTrainData>>
  > = ({ signal }) => getUserTrainData(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserTrainData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserTrainDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserTrainData>>
>;
export type GetUserTrainDataQueryError =
  | GetUserTrainData401
  | GetUserTrainData500;

export function useGetUserTrainData<
  TData = Awaited<ReturnType<typeof getUserTrainData>>,
  TError = GetUserTrainData401 | GetUserTrainData500,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserTrainData>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTrainData>>,
          TError,
          Awaited<ReturnType<typeof getUserTrainData>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserTrainData<
  TData = Awaited<ReturnType<typeof getUserTrainData>>,
  TError = GetUserTrainData401 | GetUserTrainData500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserTrainData>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTrainData>>,
          TError,
          Awaited<ReturnType<typeof getUserTrainData>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserTrainData<
  TData = Awaited<ReturnType<typeof getUserTrainData>>,
  TError = GetUserTrainData401 | GetUserTrainData500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserTrainData>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get train data for the authenticated user
 */

export function useGetUserTrainData<
  TData = Awaited<ReturnType<typeof getUserTrainData>>,
  TError = GetUserTrainData401 | GetUserTrainData500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserTrainData>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserTrainDataQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Chat with AI personal trainer
 */
export const chatWithAi = (
  chatWithAiBody: ChatWithAiBody,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>({
    url: `/ai/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: chatWithAiBody,
    signal,
  });
};

export const getChatWithAiMutationOptions = <
  TError = ChatWithAi401 | ChatWithAi500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatWithAi>>,
    TError,
    { data: ChatWithAiBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatWithAi>>,
  TError,
  { data: ChatWithAiBody },
  TContext
> => {
  const mutationKey = ["chatWithAi"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatWithAi>>,
    { data: ChatWithAiBody }
  > = (props) => {
    const { data } = props ?? {};

    return chatWithAi(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatWithAiMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatWithAi>>
>;
export type ChatWithAiMutationBody = ChatWithAiBody;
export type ChatWithAiMutationError = ChatWithAi401 | ChatWithAi500;

/**
 * @summary Chat with AI personal trainer
 */
export const useChatWithAi = <
  TError = ChatWithAi401 | ChatWithAi500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatWithAi>>,
      TError,
      { data: ChatWithAiBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof chatWithAi>>,
  TError,
  { data: ChatWithAiBody },
  TContext
> => {
  return useMutation(getChatWithAiMutationOptions(options), queryClient);
};
